### ISSUE TITLE
DIN1 never change

### ISSUE THREAD

**Issue by ptorrent** [monarco/monarco-hat-driver-nodejs#1]
Hello,

I have a problem with the driver. Maybe I'm doing something wrong. I can not change the value of my digital input. I plugged a cable in the 24v output and connected it to DIN1. I do not see any changes ?

DI1..4: **0000** | CNT1: 00000 | CNT2: 65535 | AIN1: 0.000 | AIN2: 0.000
DI1..4: **0000** | CNT1: 00000 | CNT2: 65535 | AIN1: 0.000 | AIN2: 0.000
DI1..4: **0000** | CNT1: 00000 | CNT2: 65535 | AIN1: 0.000 | AIN2: 0.000

Thank you in advance for your answer

**Comment by vstk** [comment]
Hello,

the digital inputs on the Monarco HAT are isolated. It means they have separated COM potential from the power supply ground. In your case, you have to connect GND (13) and DIN-COM (15) terminals together. Are they connected?

**Comment by ptorrent** [comment]
Hello,

It's perfect. Now it's work !

Thanks a lot ! Have a nice day
