### ISSUE TITLE
ERROR: Failed CRC Check on received message.

### ISSUE THREAD

**Issue by ptorrent** [monarco/monarco-hat-driver-nodejs#2]
Hello,

When I launch the demo , I got this error...

----

root@WBox:/plugins/pluginch/lib/monarcoLib/monarco-hat-driver-nodejs# npm install
npm WARN package.json monarco@1.0.0 No repository field.
npm WARN package.json monarco@1.0.0 license should be a valid SPDX license expression
root@WBox:/plugins/pluginch/lib/monarcoLib/monarco-hat-driver-nodejs# node index.js
Monarco HAT Node.js library 'demo' example v1.0
Cycle interval: 70 [ms]
ERROR: Failed CRC Check on received message.

-----

Any idea ? Thanks for your help !

**Comment by rexcontrols** [comment]
Hi,
sorry to hear about the difficulties. Can you please check/try the following:
- Is there any other program/service accessing the SPI bus on your Raspberry Pi?
- Can you try running the [C  example from the neighboring repo](https://github.com/monarco/monarco-hat-driver-c)? 
- Can you try starting from a fresh OS image? What distribution are you using?

I just tried with a fresh Raspbian Stretch image from 2017-09-07 and I got it working using the instructions from the readme.md file.

Let me know...

**Comment by ptorrent** [comment]
Hello

Thanks for your reply.

I do not know what happened. We launched the demo on a Raspberry. We restarted the test several times and suddenly everything worked. Maybe the system was not ready.

We work with your device on our product for several weeks and everything seems to work perfectly.

Thanks a lot for your work.
