### ISSUE TITLE
Digital output 

### ISSUE THREAD

**Issue by ptorrent** [monarco/monarco-hat-driver-nodejs#3]
Hello,

I'm using DOUT1,2,3,4. 

When I activate the output, I have 5 V. When I plug a 5 V relay, it never triggers and I have ~1V per output...

Digital Input working well.

What am I doing wrong?

Thanks for your help !

**Comment by ghost** [comment]
Hello,
DOUTs work only as very weak 5V sources, which is sufficient for e.g. TTL logic circuits. For switching loads, you must use the DOUT as sink, it is an open collector, switching to GND.

See section 3.2.4 of the [Monarco HAT Hardware reference guide](https://github.com/monarco/monarco-hat-documentation/blob/master/Monarco_HAT_Hardware_Reference_Manual.pdf), namely image 3.5, DOUT1. You will need an external 5V power supply.

Alternatively you can switch to 12V or 24V relays, depending on the power source of your setup. That way you could power both the Monarco HAT and the relays from the same power supply.

Hope this helps, let me know.

With kind regards,
Jaroslav

**Comment by ptorrent** [comment]
Hello,

 

I'm sorry but I really do not understand. Before Monarco Hat, we used the raspberry Piface (power supply 5V 8 DO / DI) and it worked very well. We went on Monarco for the din rail version and more professional. What’s the difference between PiFace DO and Monarco Hat DO ?

 

 

 

Meilleures salutations.

____________________________

 

Torrent Patrick

 

Weble Sàrl

Web :  <http://www.weble.ch> http://www.weble.ch

Tél. : +41792657982

Mail :  <mailto:ptorrent@weble.ch> ptorrent@weble.ch

**Comment by ghost** [comment]
Hi again,
the DO of PiFace Digital works as **source** for the 5V circuit with the relay coil. 

On the contrary, the DO of the Monarco HAT is designed as **sink**, it works as GND for the 5V circuit with the relay coils.

If you can send your circuit schematics with PiFace Digital, I'll prepare the schematics with Monarco HAT for you. Btw, what relays are you trying to control?

Let me know and I'll be happy to help.

**Comment by ptorrent** [comment]
Hi again,

Thanks for your reply !

We are using this relay:

http://www.distrelec.ch/fr/Relais-semiconducteurs-monophas%C3%A9s-4-32-VDC-5-A-Crouzet-84-130-105/p/13743820?q=Base+relais+din&filter_Tension+d%27entr%C3%A9e~~VDC=4...32&page=2&origPos=18&origPageSize=10&simi=89.26#download


![schema](https://user-images.githubusercontent.com/6083644/35520686-057ef502-0518-11e8-85cb-d2d9ac437ce2.png)

**Comment by ghost** [comment]
OK, the relay accepts 4..32VDC control signal, therefore this should work for you:
![monarco-hat-dout-relay-coil](https://user-images.githubusercontent.com/35925970/35521916-49400cb0-051b-11e8-956f-5a7977f2d39a.png)

Does it fix the issue?
